spring:
  application:
    name: surveyor

  datasource:
    url: jdbc:postgresql://localhost:5432/surveyor
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


